[package]
name = "labels"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.7"
minifb = { version = "0.17", default-features = false, features = ["x11"] }
ab_glyph = "0.2.28"
rustyline = "14.0.0"
image-webp = "0.1.3"
once_cell = "1.20.1"

[workspace]
resolver = "2"
members = [".", "iconTools/tools"]
