[package]
name = "labels"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = { version = "0.7", default-features = false, features = [
    "safe_arch",
    "simd",
    "std",
] }
minifb = { version = "0.17", default-features = false, features = ["x11"] }
ab_glyph = "0.2.28"
image-webp = "0.1.3"
bytes = "1.7.2"
tar-wasi = "0.4.38"
attohttpc = { version = "0.28.0", default-features = false, features = [
    "tls-rustls-webpki-roots",
] }
tinyjson = "2.5.1"
anyhow = "1.0.89"
rustls = "0.23.14"
rustls-native-certs = "0.8.0"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[profile.release.package.tar-wasi]
opt-level = 3

[profile.dev.package.tar-wasi]
opt-level = 3

# [workspace]
# resolver = "2"
# members = [".", "iconTools/tools"]
