[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
rayon = "1.10.0"
resvg = "0.44.0"
serde = "1.0.210"
serde_json = "1.0.128"
tar = "0.4.42"
tokio = { version = "1.40.0", features = ["full"] }
